on:
  push:
    branches:
      - master

name: Deploy

env:
  RUSTDOCFLAGS: "--cfg docsrs"

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@be39649afda95dbf70f87cce95f68b8d5797b296 # nightly
        with:
          toolchain: nightly

      - name: Install qlog-dancer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libexpat1-dev libfreetype6-dev libfontconfig1-dev

      - name: Run cargo doc
        run: cargo doc --no-deps --all-features

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@1d6ee9b181a81033a16bd707a1401afa978daab4 # v5
        with:
          target_branch: gh-pages
          build_dir: target/doc
          fqdn: docs.quic.tech
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Build Docker images
        run: make docker-build

      - name: Login to DockerHub
        if: env.DOCKER_USERNAME != '' && env.DOCKER_TOKEN != ''
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Publish Docker images
        if: env.DOCKER_USERNAME != '' && env.DOCKER_TOKEN != ''
        run: make docker-publish
